apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - name: http
    nodePort: 31704
    port: 8080
    protocol: TCP
    targetPort: 80


#kubectl create -f loadbalancer.yaml

#kubectl expose deployment nginx-deployment  --type=LoadBalancer  --name=nginx-service
